input_filename: '/Users/renero/Code/SA_PoC/model/model_evaluation/bilstm_crf/input/resultado_cruce.csv'

# Tags to be used by this network
tag_header: 'tag_condicionante'
amr_header: 'amr_condicionante'

# What tags do I want to use for prediction with this network?
amr:
  'x': 'O'
  'ca': 'C-AFIRM'
  'cc': 'C-CENTRO'
  'cd': 'C-DIRECC'
  'ci': 'C-INFO_USR'
  'cn': 'C-NEG'
  'cp': 'C-PAIS'
  'ct': 'C-TTO'
  'cu': 'C-USER'

# Specify which one is the wildcard tag not carrying encoding.
void_tag: 'x'

output_vocabulary: '/Users/renero/Code/SA_PoC/results/trained_networks/diccionario_cond.txt'
def_nn_name: '/Users/renero/Code/SA_PoC/results/trained_networks/dnn_conds.h5'
def_tokenizer_name: '/Users/renero/Code/SA_PoC/results/trained_networks/tokenizer_cond.pickle'

max_utt_len: 38
test_size: 0.05
CRF: True

UNK: '_UNK'
UNK_ID: 0

max_vocabulary_size: 0
vocabulary_size: 4000
batch_size: 128
validation_split: 0.1
num_epochs: 1
