working_path: '/Users/renero/Code/BOTs/BOT_PoC/model/model_evaluation/01_Entrenamiento/01_BILSTM_objeto'
input_filename: 'resultado_cruce.csv'
output_vocabulary: 'diccionario.txt'
def_nn_name: './output/BI_LSTM_entities.h5'
largo_max: 40
test_size: 0.05
num_tags: 6
CRF: True

_PAD: '_PAD'
_GO: '_GO'
_EOS: '_EOS'
_UNK: '_UNK'
_START_VOCAB: [_PAD, _GO, _EOS, _UNK]

PAD_ID: 0
GO_ID: 1
EOS_ID: 2
UNK_ID: 3

max_vocabulary_size: 0
vocabulary_size: 4000
batch_size: 128
validation_split: 0.1
num_epochs: 1
