input_filename: '/Users/renero/Code/SA_PoC/model/model_evaluation/bilstm_crf/input/resultado_cruce.csv'

# Tags to be used by this network
tag_header: 'tag_objeto'
amr_header: 'amr_objeto'

amr:
  'x': 'O'
  'ot': 'O-TARJETA'
  'oc': 'O-COBERTURA'
  'oh': 'O-CENTROS'
  'or': 'O-REEMBOLSO'
  'os': 'O-SEGURO'

# Specify which one is the wildcard tag not carrying encoding.
void_tag: 'x'

output_vocabulary: '/Users/renero/Code/SA_PoC/results/trained_networks/diccionario_entities.txt'
def_nn_name: '/Users/renero/Code/SA_PoC/results/trained_networks/dnn_entities.h5'
def_tokenizer_name: '/Users/renero/Code/SA_PoC/results/trained_networks/tokenizer_entities.pickle'

max_utt_len: 38
test_size: 0.05
CRF: True

UNK: '_UNK'
UNK_ID: 0

max_vocabulary_size: 0
vocabulary_size: 4000
batch_size: 128
validation_split: 0.1
num_epochs: 1
