working_path: '/Users/renero/Code/SA_PoC/model/model_evaluation/bilstm_crf'
input_filename: 'resultado_cruce.csv'

# Tags to be used by this network
tag_header: 'tag_accion'
amr_header: 'amr_accion'

# What tags do I want to use for prediction with this network?
learn_tags:
  - 'x'
  - 'aa'
  - 'ac'
  - 'ad'
  - 'ae'
  - 'ai'
  - 'an'
  - 'ar'
  - 'asi'
  - 'asr'
  - 'asnc'

amr:
  'x': 'O'
  'aa': 'A-AMPL'
  'ac': 'A-CADC'
  'ad': 'A-ERR_DAT'
  'ae': 'A-ERR_FUNC'
  'ai': 'A-INFO'
  'an': 'A-NEWUSR'
  'ar': 'A-ROBO'
  'asi': 'A-INC_BNF'
  'asr': 'A-RENOV'
  'asnc': 'A-CANC'

# Specify which one is the wildcard tag not carrying encoding.
void_tag: 'x'

output_vocabulary: 'diccionario_actions.txt'
def_nn_name: './output/dnn_actions.h5'
def_tokenizer_name: './output/tokenizer_actions.pickle'

max_utt_len: 38
test_size: 0.05
CRF: True

_PAD: '_PAD'
_GO: '_GO'
_EOS: '_EOS'
_UNK: '_UNK'
_START_VOCAB: [_PAD, _GO, _EOS, _UNK]

PAD_ID: 0
GO_ID: 1
EOS_ID: 2
UNK_ID: 3

max_vocabulary_size: 0
vocabulary_size: 4000
batch_size: 128
validation_split: 0.1
num_epochs: 1
